cascara_version = 0.10.0
version = 0.10.0
group = io.github.qishr
url = https://qishr.github.io/
scm_url = https://github.com/qishr/cascara-lang-ct
scm_conn = scm:git:https://github.com/qishr/cascara-lang-ct.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-lang-ct.git
org.gradle.configuration-cache = false