
plugins {
    id 'java'
    id 'java-gradle-plugin'
    id("com.gradle.plugin-publish") version "1.2.1"
}

group = 'io.qishr.github'
version = '0.1.0'


tasks.withType(JavaCompile).configureEach {
    options.release = 21
}


repositories {
	mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(platform("io.github.qishr:cascara-meta-bom:0.1.21"))
    implementation "io.github.qishr:cascara-common"

    implementation(project(":ct-dsl"))
}

gradlePlugin {
    website = "https://github.com/qishr/cascara-gradle-ct"
    vcsUrl = "https://github.com/qishr/cascara-gradle-ct"
    plugins {
        javaLibraryConventions {
            id = "io.github.qishr.cascara-gradle-plugins.ct"
            implementationClass = "io.github.qishr.cascara.gradle.ct.CtPlugin"
            displayName = "Cascara CT DSL"
            description = "Color Transformation DSL"
            tags = ["java-setup", "api-configuration", "test-setup", "jar-manifest", "toolchain-configuration"]
        }
    }
}

