version = 0.1.0
java_name = cascara.lang.ct
maven_name = cascara-lang-ct
group = io.github.qishr
title = Color Transformation DSL
description = Color Transformation DSL
url = https://qishr.github.io/
scm_url = https://github.com/qishr/cascara-lang-ct
scm_conn = scm:git:https://github.com/qishr/cascara-lang-ct.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-lang-ct.git

org.gradle.configuration-cache = false
